### PR TITLE
pre-commit hooks

### PR DESCRIPTION
**Pull request by mfine**
Copy everything in the hooks directory with `make hooks`.

/cc @mookerji @JoshuaGross

### CODE REVIEW

**Comment by mfine** [comment]
Putting general comments here:

+ Doesn't run hooks on every action, so can't be sure the hooks ever get installed without use explicitly running hooks.
+ Runs tests before commit - is that a good idea? Better before the commit than on travis?

**Comment by mfine** [comment]
Also, maybe it should be:

```make
hooks:
    cp hooks/* "$(git rev-parse --git-dir)/hooks"
```

**Comment by mookerji** [comment]
I always thought pre-commit hooks were a bit weird, particularly for running tests that could take a while when you're committing frequently. What about a pre-push hook?

**Comment by JoshuaGross** [comment]
I'm fine with this as pre-push or pre-commit.

Why don't we run this on `make test` as well? We already know that we need tests to pass before pushing, so taking care of everything on that step would be nice.

**Comment by mfine** [comment]
Can pre-push modify code? Maybe we do the modifiers (stylish, lint) in pre-commit, and run make test in pre-push?

**Comment by JoshuaGross** [comment]
If the hooks modify code, they still need to be `git add`ed to the repository. Anyway, none of our hooks should be modifying code? We should just fail the hook if someone happens with stylish/lint or if `make test` fails.

**Comment by mfine** [comment]
Hmm, good point - stylish modifies code - I was thinking it would fix stuff into the commit, but that might not be right.

**Comment by mfine** [comment]
Added a pre-push hook for the frequent committers. Bringing this in.

**Pull request merged**
