### PR TITLE
Add --ddb-port option to enable local DDB access for testing.

### PR DESCRIPTION
**Pull request by ejconlon**

### CODE REVIEW

**Comment by mfine** [comment]
:shipit:

**Comment by JoshuaGross** [comment]
Hmmm. I feel like it makes more sense to just have `ddbPort` and `ddbHost` as config options, since the behavior of this will appear mystical from the outside. (Why is the port set? Where's the host? Why is the server acting this way? etc)

**Comment by mfine** [comment]
What other ddb host are we thinking about using besides localhost?

Think this should be limited to an optional port that signifies to run ddb locally on that given port.

**Comment by JoshuaGross** [comment]
I think we should either treat it as a binary (`ddbTestMode=true/false`) or expose both `host` and `port`, since both of those are pretty self-explanatory if you're just looking at env vars/config files/etc.

**Comment by mfine** [comment]
Yeah, my first preference was a ddbLocal flag. But Eric wants to be able to run multiple ddb instances - which now that I'm saying it out loud doesn't seem to make as much sense - and in that case it made more sense to have an optional port on localhost and not include all the options that can be set on an endpoint.

**Comment by mfine** [comment]
:+1: on a `--ddbLocal` or `--localDdb` switch flag (see `--metrics` for another existing example of a switch flag). I think we should only run one local dynamodb instance at a time at a known default location, e.g., localhost:8000. If there are concerns about running multiple things at once, e.g., api and integration tests, then we can multi-tenant it - the provision scripts can start local dynamo db if it's not up (or we can even have a dynamodb daemon assumption, like we did with postgres), and we can salt table names to avoid conflicts, e.g., integration tests create tables like with names like `session-test-<uid>`.

**Comment by ejconlon** [comment]
Not really into the idea of making this LESS functional, also not really into the idea of spending more time on this, there are other things to do.

**Comment by mookerji** [comment]
Feel free to merge it once Travis signs off.

**Comment by mfine** [comment]
@ejconlon less about removing functionality, and more about having a good convention around local ddb usage. If you have a configurable port, it's a little confusing that it's indicating that you're going to actually use a local ddb port if that's set (mild argument), also suggesting you could run multiple ddb instances (stronger argument - though even local ddb itself has a configurable port). See https://github.com/ejconlon/skylark-core/pull/1/files

**Comment by ejconlon** [comment]
Not dropping the issue, but also not fixing in this PR, I have a lot to do today.

**Pull request merged**
